---
name: on_hello_event1
pack: canonneventmanager
description: Sample rule firing on canonneventmanager.event1.
enabled: true
trigger:
    type: canonneventmanager.event1
action:
    ref: canonneventmanager.greet
    parameters:
        greeting: Helloo
